@Restaurants.API_HostAddress = https://localhost:5001
@token=CfDJ8GMvchXJt85Hl76HEG1NLkt3faV4s2uzp8V5oQZSQHSuqd1MhnD3_aeDAx4pGMhXNsChUQFDbKSZA7ysbD72tNLHe7QIjXUm8XyAzVFIQVW2z8DbGS1brMrmF_bTb_VEpHUh_V3owR5jkY2NlC0eCMkGS9L-2fz9GvK0hBcSf5UwdBomoffPjxlqbsKaHJ7ZoSOHZkiPlMxzIeFfP0MUxsGQabNVGDr3Ean3K-Vf1YaFzgcL2DBdJPIz4p8IGUUiXlL_XWcrUgAnb8T1M8Ja2qJlwqEHh0HDJpNUOwjzaARgO12-yI1qfKLeY7exBY1wx7tyqEixn8a9os15dj7fhHkKrY9r9ZJIy0MVI7bpKY0j1-6FY0-H4Tx1GA_XKwurZ-plnKSSb7tMxAtoAep0LcSuBVbtqoctStwJVJwLL2dlhEtkRV9BOrbo4Oi5DzQYCV9FtgmTh-hWsq76upRielOQrlPPOqvuIvjBIiAN1ScZi1-m8Z-4h5bjGuT2fcCdg1PRsx1kjb1TpdH5dRLSv5h53kwgvOAhPlpUiC7xDXs6lheq8e6tR4jlt7PTGLsB0z9pB_CImPc2Z2qwoPzGDrnIECPqLqHf9aM8lqR2Tk6rkF9N32HLmHNtTxAn_Sr7uu3o3ZdGx9gOYr9JzYNkTxdvqqEqpDbgh2gTNKU3_3xxXKWIG_S-lyt0v0A57Yr5EiW8HAkI4kxiGfYwcnekbqoBY-0cPl-GJEdXndxo5lQgKl40iNXjV3qVA7AcaNFonjn9gnBt-e6Izs2Pw-3n_bUAeTMCatKp-2Y5TOBJEdH4
GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3
Authorization: Bearer {{token}}


###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "Name": "Spicy Delights",
   "Description": "A culinary experience like no other",
   "Category": "Mexican",
   "HasDelivery": true,
   "ContactEmail": "info@gourmetdelights.com",
   "ContactNumber": "555-123-4567",
   "City": "Metropolis",
   "Street": "456 Gourmet Avenue",
   "PostalCode": "54-321"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{restaurantId}/dishes/{dishId:int}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{restaurantId}/dishes

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/{restaurantId}/dishes
Content-Type: application/json

{
  //CreateDishCommand
}

###

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "owner@gmail.com",
  "password": "Fawzi123#"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "fawzi@gmail.com",
  "password": "Fawzi123#"
}